=== kharebavagiorgi/library/src/main/resources/library.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.library.com/schema"
           xmlns="http://www.library.com/schema"
           elementFormDefault="qualified">

    <xs:simpleType name="GenreType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="FICTION"/>
            <xs:enumeration value="NON_FICTION"/>
            <xs:enumeration value="SCIENCE"/>
            <xs:enumeration value="HISTORY"/>
            <xs:enumeration value="ART"/>
            <xs:enumeration value="EDUCATION"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="AddressType">
        <xs:attribute name="id" type="xs:long" use="optional"/>
        <xs:attribute name="street" type="xs:string" use="required"/>
        <xs:attribute name="city" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="ReviewType">
        <xs:sequence>
            <xs:element name="rating" type="xs:int"/>
            <xs:element name="comment" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="optional"/>
    </xs:complexType>

    <xs:complexType name="UserType">
        <xs:sequence>
            <xs:element name="registrationDateTime" type="xs:dateTime"/>
            <xs:element name="address" type="AddressType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="optional"/>
        <xs:attribute name="isActive" type="xs:boolean" use="required"/>
    </xs:complexType>

    <xs:complexType name="BookType">
        <xs:sequence>
            <xs:element name="id" type="xs:long" minOccurs="0"/>
            <xs:element name="isbn" type="xs:string" minOccurs="0"/>
            <xs:element name="title" type="xs:string" minOccurs="0"/>
            <xs:element name="publicationDate" type="xs:date" minOccurs="0"/>
            <xs:element name="pageCount" type="xs:int" minOccurs="0"/>
            <xs:element name="genre" type="GenreType" minOccurs="0"/>
            <xs:element name="reviews">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="review" type="ReviewType" maxOccurs="unbounded" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DepartmentType">
        <xs:sequence>
            <xs:element name="book" type="BookType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="optional"/>
        <xs:attribute name="name" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="EmployeeType">
        <xs:sequence>
            <xs:element name="firstName" type="xs:string" minOccurs="0"/>
            <xs:element name="lastName" type="xs:string" minOccurs="0"/>
            <xs:element name="departmentId" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="optional"/>
    </xs:complexType>

    <xs:element name="library">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="books">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="book" type="BookType" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="users">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="user" type="UserType" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="departments">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="department" type="DepartmentType" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="employees">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="employee" type="EmployeeType" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:long" use="optional"/>
            <xs:attribute name="name" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== kharebavagiorgi/library/src/main/resources/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<library id="1" name="City Central Library"
         xmlns="http://www.library.com/schema"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.library.com/schema library.xsd">

    <books>
        <book>
            <id>1</id>
            <isbn>978-0321765723</isbn>
            <title>The Art of Programming</title>
            <publicationDate>2011-05-25</publicationDate>
            <pageCount>888</pageCount>
            <genre>SCIENCE</genre>
            <reviews>
                <review id="1">
                    <rating>5</rating>
                    <comment>Excellent resource.</comment>
                </review>
            </reviews>
        </book>
        <book>
            <id>4</id>
            <isbn>978-0451524823</isbn>
            <title>A Study in Scarlet</title>
            <publicationDate>1887-12-01</publicationDate>
            <pageCount>128</pageCount>
            <genre>FICTION</genre>
            <reviews>
                <review id="50">
                    <rating>5</rating>
                    <comment>The introduction to the legendary detective and his loyal companion.</comment>
                </review>
                <review id="51">
                    <rating>4</rating>
                    <comment>A classic start to the Holmes saga.</comment>
                </review>
            </reviews>
        </book>
    </books>

    <users>
        <user id="101" isActive="true">
            <registrationDateTime>2023-01-15T10:30:00</registrationDateTime>
            <address id="501" street="Main St 101" city="Metropolis"/>
        </user>
    </users>

    <departments>
        <department id="201" name="Science &amp; Tech">
            <book>
                <id>1</id>

                <isbn>978-0321765723</isbn>

                <title>The Art of Programming</title>

                <publicationDate>2011-05-25</publicationDate>

                <pageCount>888</pageCount>

                <genre>SCIENCE</genre>

                <reviews>
                    <review id="1">
                        <rating>5</rating>
                        <comment>Excellent resource.</comment>
                    </review>
                </reviews>
            </book>
        </department>
    </departments>

    <employees>
        <employee id="301">
            <firstName>Alice</firstName>
            <lastName>Smith</lastName>
            <departmentId>D001</departmentId>
        </employee>
    </employees>
</library>
